version: '3'

tasks:
  default:
    cmds:
      - task --list

  run:
    desc: Runs the script with the provided name (clean, upgrade, install)
    cmds:
      - sh scripts/{{.CLI_ARGS}}.sh

  setup:
    desc: Starts the required docker services & seeds the database
    cmds:
      - docker compose -f  backend/docker/docker-compose.dev.yml --env-file backend/app/.env.development -p trophoria-dev up -d
      - sleep 5
      - cd backend/app && bun drizzle:migrate

  stop:
    desc: Stops the dev environment
    cmds:
      - docker compose -f  backend/docker/docker-compose.dev.yml --env-file backend/app/.env.development -p trophoria-dev down
