version: '3'

tasks:
  build-container:
    cmds:
      - docker build -f backend/docker/Dockerfile -t devtobias/trophoria backend

  start-container:
    cmds:
      - docker run --env-file backend/app/.env.development -p 8080:8080 devtobias/trophoria

  setup-development:
    cmds:
      - docker compose -f  backend/docker/docker-compose.dev.yml --env-file backend/app/.env.development -p trophoria-dev up -d
