version: '3'

services:
  database:
    image: postgres:alpine
    restart: unless-stopped
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB}
    networks:
      - trophoria-network
    volumes:
      - postgres-data:/data/postgres

networks:
  trophoria-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
